[build]
  command   = "echo \"No build needed\""
  publish   = "."                     # serve everything from project root
  functions = "netlify/functions"     # your serverless lambdas

[[plugins]]
  package = "@netlify/plugin-sitemap"
  [plugins.inputs]
    # Base URL of your live site
    baseUrl    = "https://lailahaillallah.netlify.app"
    # Directory to crawl (the same as your publish dir)
    buildDir   = "."

    # Exclude only your 404 page (everything else is included)
    exclude    = ["**/404.html"]

    # Default change frequency and priority for all entries
    changeFreq = "monthly"
    priority   = 0.5

    # How to treat .html files in URLs
    prettyURLs = true

    # Output file name (defaults to "sitemap.xml")
    filePath   = "sitemap.xml"